### ISSUE TITLE
Login fails

### ISSUE THREAD

**Issue by Palatis** [cage1016/GDCLauncher#1]
I recently got a new comp so I have to re-login to the GDC in the GDCLauncher.
But whenever I click on the "Login Google Account First", and then login into the webpage that popped up, it brings me to
https://myaccount.google.com/
instead of actually login in GDCLauncher.

GDCLauncher stays un-logged in.

I'm using Chromium on Linux, user agent
`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/51.0.2704.79 Chrome/51.0.2704.79 Safari/537.36`

**Comment by cage1016** [comment]
@Palatis Thanks for feedback. New version [v1.0.1](https://chrome.google.com/webstore/detail/gdclauncher/bicgkglnnilldakpenngnblekooejnpg) fixed login fail error cause GCP console renew. Just publish earlier. Please let me know if this version fixed your problem.  :-)

I have a plan to renew this extension in the future.

**Comment by Palatis** [comment]
Yeah fixed, thx.
